export const translations = {
  en: {
    brand: "Herman Signature Coffee",
    terminal: "Abidjan Central Terminal",
    beans: "100% Ivorian Beans",
    systemStatus: "System: Live & Syncing",
    clubName: "Signature Brew Club",
    memberId: "Member ID",
    since: "Since",
    premiumClub: "Premium Club",
    referralCode: "Your Referral Code",
    referralBonus: "Share with friends to earn points",
    rewardsJourney: "Loyalty Journey",
    pointsBalance: "Points Balance",
    foundersBonus: "Founders Bonus Active",
    recentPerks: "Recent Perks",
    unclaimed: "Unclaimed Rewards",
    personalized: "Personalized For You",
    claimOffer: "Claim Signature Offer",
    recordDrink: "Record Signature Drink",
    redeemItem: "Redeem Free Item",
    newRegistration: "New Registration",
    dailyRevenue: "Daily Revenue",
    conversion: "Loyalty Conversions",
    clv: "CLV (Lifetime)",
    activityFeed: "Live Activity Feed",
    event: "Event",
    member: "Member",
    status: "Status",
    time: "Time",
    addWallet: "Add to Apple Wallet",
    done: "Done",
    backToClub: "Back to Club",
    verified: "Passport Verified",
    activePass: "Digital Signature Brew Pass Active",
    memberInfo: "Member Information",
    regIn: "Registered In",
    cancel: "Cancel",
    register: "Register",
    fullName: "Full Name",
    phone: "Phone Number",
    email: "Email Address",
    joinDate: "Join Date",
    lastVisit: "Last Visit",
    referredBy: "Referred By (Optional Code)",
    mailLog: "Email Notification Log",
    to: "To",
    subject: "Subject",
    message: "Message",
    referralDetails: "Refer friends (+50 pts) • They get (+25 pts)",
    tierBenefits: "Current Tier Benefits",
    exclusiveOffer: "Exclusive Member Offer",
    activeLive: "Live Updates: Active",
    connecting: "Connecting..."
  },
  fr: {
    brand: "Herman Signature Café",
    terminal: "Terminal Central d'Abidjan",
    beans: "Grains 100% Ivoiriens",
    systemStatus: "Système : En Direct et Synchronisé",
    clubName: "Club Signature Brew",
    memberId: "ID Membre",
    since: "Depuis",
    premiumClub: "Club Premium",
    referralCode: "Votre Code de Parrainage",
    referralBonus: "Partagez avec des amis pour gagner des points",
    rewardsJourney: "Parcours de Fidélité",
    pointsBalance: "Solde de Points",
    foundersBonus: "Bonus Fondateur Actif",
    recentPerks: "Avantages Récents",
    unclaimed: "Récompenses non Réclamées",
    personalized: "Personnalisé Pour Vous",
    claimOffer: "Réclamer l'Offre Signature",
    recordDrink: "Enregistrer une Boisson",
    redeemItem: "Utiliser une Récompense",
    newRegistration: "Nouvelle Inscription",
    dailyRevenue: "Revenu Quotidien",
    conversion: "Conversions de Fidélité",
    clv: "CLV (Vie du Client)",
    activityFeed: "Flux d'Activité en Direct",
    event: "Événement",
    member: "Membre",
    status: "Statut",
    time: "Heure",
    addWallet: "Ajouter à Apple Wallet",
    done: "Terminé",
    backToClub: "Retour au Club",
    verified: "Passeport Vérifié",
    activePass: "Pass Digital Signature Brew Actif",
    memberInfo: "Informations Membre",
    regIn: "Inscrit à",
    cancel: "Annuler",
    register: "S'inscrire",
    fullName: "Nom Complet",
    phone: "Numéro de Téléphone",
    email: "Adresse Email",
    joinDate: "Date d'Adhésion",
    lastVisit: "Dernière Visite",
    referredBy: "Parrainé par (Code Optionnel)",
    mailLog: "Journal des Notifications Email",
    to: "À",
    subject: "Sujet",
    message: "Message",
    referralDetails: "Parrainez des amis (+50 pts) • Ils reçoivent (+25 pts)",
    tierBenefits: "Avantages du Niveau Actuel",
    exclusiveOffer: "Offre Membre Exclusive",
    activeLive: "Mises à jour en direct : Actif",
    connecting: "Connexion..."
  }
};

export type Language = 'en' | 'fr';
